export const movieAccessToken =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlNzcyNmJjNGQyYzEzNjAzYmQ1MzUxNWQwYTYwYjk0NSIsInN1YiI6IjY0ZGRhZTliNTllOGE5MDBhYzA4NjZkMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.6urMWfC9-9d74bWirrUeNKjOcYuDWyRS0joCThaezaM";
